import org.gradle.api.attributes.plugin.GradlePluginApiVersion

plugins {
    id 'com.gradle.plugin-publish'
    id 'org.gradle.plugin-compatibility'
    id 'java-library'
    id 'maven-publish'
    id 'java-gradle-plugin'
}

java{
    toolchain.languageVersion = JavaLanguageVersion.of(21)
    withSourcesJar()
    withJavadocJar()
    registerFeature("metadata") {
        usingSourceSet(sourceSets.create("metadata"))
        withSourcesJar()
        withJavadocJar()
    }
}

abstract class NamedTransformer<A extends Named> implements Transformer<A, String> {
    private final Class<A> clazz

    @Inject
    protected abstract ObjectFactory getObjectFactory()

    @Inject
    NamedTransformer(Class<A> clazz) {
        this.clazz = clazz
    }

    @Override
    A transform(String s) {
        return objectFactory.named(clazz, s)
    }
}

['apiElements', 'runtimeElements'].each {
    configurations.named(it).configure {
        attributes {
            attributeProvider(
                GradlePluginApiVersion.GRADLE_PLUGIN_API_VERSION_ATTRIBUTE,
                libs.versions.gradle.map(objects.newInstance(NamedTransformer, GradlePluginApiVersion))
            )
        }
    }
}

dependencies {
    compileOnly(libs.gradle) {
        capabilities {
            requireFeature "internal"
        }
    }

    metadataCompileOnly(libs.gradle) {
        capabilities {
            requireFeature "internal"
        }
    }

    metadataApi(project(":"))
}

// Thanks, java-gradle-plugin... but no thanks
configurations.named("compileOnlyApi") {
    withDependencies {
        it.removeElement(project.dependencies.gradleApi())
    }
}

def pluginIdToVariant(PluginDeclaration decl, String feature) {
    def pluginId = decl.id
    def softwareComponentFactory = project.publishing.softwareComponentFactory
    def sanePluginId = pluginId.split("\\.").collect { it.capitalize() }.join("")
    def adhocComponent = softwareComponentFactory.adhoc("plugin${sanePluginId}")
    project.components.add(adhocComponent)
    def depScope = configurations.dependencyScope("plugin${sanePluginId}Dependencies")
    def consumable = configurations.consumable("plugin${sanePluginId}Runtime") {
        extendsFrom depScope
        attributes {
            attribute(Usage.USAGE_ATTRIBUTE, objects.named(Usage.class, Usage.JAVA_RUNTIME))
            attribute(Category.CATEGORY_ATTRIBUTE, objects.named(Category.class, Category.LIBRARY))
            attributeProvider(
                GradlePluginApiVersion.GRADLE_PLUGIN_API_VERSION_ATTRIBUTE,
                libs.versions.gradle.map(objects.newInstance(NamedTransformer, GradlePluginApiVersion))
            )
        }
        outgoing {
            capability("${pluginId}:${pluginId}.gradle.plugin:${project.version}")
        }
    }
    adhocComponent.addVariantsFromConfiguration(consumable.get()) {
        mapToMavenScope("runtime")
    }
    dependencies.add(depScope.name, dependencies.project(":")) {
        capabilities {
            if (feature != null) {
                requireFeature feature
            }
        }
    }
    publishing.publications.matching { it.name == "${decl.name}PluginMarkerMaven" }.withType(MavenPublication).configureEach {
        from adhocComponent
        pom.withXml {
            def root = it.asElement()
            root.removeChild(root.getElementsByTagName("dependencies").item(0))
        }
        suppressAllPomMetadataWarnings()
    }
    if (feature != null) {
        tasks.named("jar", Jar) {
            exclude("META-INF/gradle-plugins/${decl.id}.properties")
        }
        var pluginDescriptorsTask = tasks.named("pluginDescriptors", GeneratePluginDescriptors)
        tasks.named("${feature.replaceAll( "(-)([A-Za-z0-9])") { Object[] it -> it[2].toUpperCase(Locale.ROOT) }}Jar", Jar) {
            from(pluginDescriptorsTask.flatMap { it.outputDirectory }.map { it.file("${decl.id}.properties") }) {
                into "META-INF/gradle-plugins"
            }
        }
    }
}

gradlePlugin {
    plugins {
        configureEach {
            compatibility.features.configurationCache = true
        }
        register("features") {
            id = "dev.lukebemish.crochet.features"
            implementationClass = "dev.lukebemish.crochet.features.FeatureRoutingPlugin"
            pluginIdToVariant(it, null)
        }
        register("featuresConvention") {
            id = "dev.lukebemish.crochet.features.convention"
            implementationClass = "dev.lukebemish.crochet.features.FeatureRoutingConventionPlugin"
            pluginIdToVariant(it, null)
        }
        register("shared") {
            id = "dev.lukebemish.crochet.base"
            implementationClass = "dev.lukebemish.crochet.CrochetSharedProjectPlugin"
            pluginIdToVariant(it, null)
        }
        register("metadata") {
            id = "dev.lukebemish.crochet.metadata"
            implementationClass = "dev.lukebemish.crochet.metadata.CrochetMetadataPlugin"
            pluginIdToVariant(it, "metadata")
        }
    }
}

tasks.register('createMinecraftLibrariesMavenContent', dev.lukebemish.crochet.buildlogic.CreateMinecraftLibrariesMavenContent) {
    className.set('dev.lukebemish.crochet.metadata.MinecraftLibrariesMavenContent')
    outputDir.set(project.file('src/metadata/java/'))
    versions.from(configurations.versionMetadataResolved)
}

publishing {
    publications {
        named {name -> name == "pluginMaven"}.withType(MavenPublication).configureEach {
            suppressAllPomMetadataWarnings()
        }
    }
}
